export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOAD_REMINDERS = 'LOAD_REMINDERS';
export const ADD_REMINDER = 'ADD_REMINDER';
export const COMPLETE_REMINDER = 'COMPLETE_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
